"""add activity section in Store

Revision ID: 9ba023ed57bd
Revises: ba07e4d5dc55
Create Date: 2021-04-30 12:10:27.920773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba023ed57bd'
down_revision = 'ba07e4d5dc55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('activity', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'activity')
    # ### end Alembic commands ###
